apiVersion: v1
kind: Namespace
metadata:
   name: nodejs

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scuserapi-app
  namespace: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scuserapi-app
  template:
    metadata:
      labels:
        app: scuserapi-app
    spec:
      containers:
      - name: scuserapi-app
        image: patriagani/sc-user-api:v1
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: scuserapi-service
  namespace: nodejs
spec:
  type: LoadBalancer
  selector:
    app: scuserapi-app
  ports:
    - port: 80
      targetPort: 3000